import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Code, Play, RefreshCw, Copy, Check, X, Laptop, Smartphone } from 'lucide-react';

export default function SandboxPreviewModal({ isOpen, onClose, initialCode }) {
  const defaultCode = initialCode || `<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: system-ui, sans-serif;
      background: #0f172a;
      color: #f8fafc;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      margin: 0;
      padding: 20px;
      box-sizing: border-box;
    }
    .card {
      background: rgba(30, 41, 59, 0.8);
      border: 1px solid rgba(148, 163, 184, 0.2);
      padding: 2rem;
      border-radius: 1rem;
      box-shadow: 0 20px 25px -5px rgba(0,0,0,0.5);
      text-align: center;
      max-w: 400px;
    }
    h1 { color: #38bdf8; margin-top: 0; }
    button {
      background: linear-gradient(135deg, #a855f7, #6366f1);
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 9999px;
      font-weight: bold;
      cursor: pointer;
      margin-top: 15px;
      transition: transform 0.2s;
    }
    button:hover { transform: scale(1.05); }
  </style>
</head>
<body>
  <div class="card">
    <h1>🚀 WaveMind Live Sandbox</h1>
    <p>Real-time client web preview generated by WaveMind AI Agent.</p>
    <button onclick="alert('Hello from WaveMind Interactive Sandbox!')">Click Interactive Test</button>
  </div>
</body>
</html>`;

  const [code, setCode] = useState(defaultCode);
  const [activeTab, setActiveTab] = useState('preview');
  const [copied, setCopied] = useState(false);
  const [deviceMode, setDeviceMode] = useState('desktop');

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-6 bg-black/80 backdrop-blur-md">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.95 }}
          className="relative w-full max-w-5xl h-[88vh] rounded-3xl bg-[#0a081d] border border-purple-500/30 shadow-2xl text-white font-sans flex flex-col overflow-hidden"
        >
          {/* Top Bar */}
          <div className="px-6 py-4 border-b border-purple-500/20 bg-purple-950/30 flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-r from-blue-500 to-purple-600 flex items-center justify-center text-white font-bold">
                <Code className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-base text-white">WaveMind Live Code Sandbox</h3>
                <p className="text-xs text-purple-300/60">Interactive real-time HTML/CSS/JS execution engine</p>
              </div>
            </div>

            {/* View Mode Switches */}
            <div className="flex items-center gap-2">
              <div className="flex bg-purple-950/60 border border-purple-500/30 rounded-xl p-1 text-xs">
                <button
                  onClick={() => setActiveTab('preview')}
                  className={`px-3 py-1 rounded-lg font-medium transition-all ${
                    activeTab === 'preview' ? 'bg-purple-600 text-white' : 'text-purple-300 hover:text-white'
                  }`}
                >
                  Live Preview
                </button>
                <button
                  onClick={() => setActiveTab('code')}
                  className={`px-3 py-1 rounded-lg font-medium transition-all ${
                    activeTab === 'code' ? 'bg-purple-600 text-white' : 'text-purple-300 hover:text-white'
                  }`}
                >
                  Source Code
                </button>
              </div>

              {activeTab === 'preview' && (
                <div className="hidden sm:flex bg-purple-950/60 border border-purple-500/30 rounded-xl p-1 text-xs">
                  <button
                    onClick={() => setDeviceMode('desktop')}
                    className={`p-1.5 rounded-lg transition-all ${
                      deviceMode === 'desktop' ? 'bg-purple-600 text-white' : 'text-purple-300 hover:text-white'
                    }`}
                    title="Desktop view"
                  >
                    <Laptop className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => setDeviceMode('mobile')}
                    className={`p-1.5 rounded-lg transition-all ${
                      deviceMode === 'mobile' ? 'bg-purple-600 text-white' : 'text-purple-300 hover:text-white'
                    }`}
                    title="Mobile view"
                  >
                    <Smartphone className="w-4 h-4" />
                  </button>
                </div>
              )}

              <button
                onClick={handleCopy}
                className="px-3 py-1.5 rounded-xl bg-purple-900/40 border border-purple-500/30 text-purple-200 hover:text-white text-xs font-semibold transition-all flex items-center gap-1.5"
              >
                {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>

              <button
                onClick={onClose}
                className="p-2 rounded-xl text-gray-400 hover:text-white hover:bg-white/10 transition-all"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Main Content Area */}
          <div className="flex-1 bg-black/40 relative overflow-hidden flex items-center justify-center p-4">
            {activeTab === 'preview' ? (
              <div
                className={`h-full transition-all duration-300 rounded-2xl overflow-hidden border border-purple-500/20 shadow-2xl bg-white ${
                  deviceMode === 'mobile' ? 'w-[375px] max-h-[667px]' : 'w-full'
                }`}
              >
                <iframe
                  title="Sandbox Live Preview"
                  srcDoc={code}
                  className="w-full h-full border-none"
                  sandbox="allow-scripts allow-modals"
                />
              </div>
            ) : (
              <textarea
                value={code}
                onChange={(e) => setCode(e.target.value)}
                className="w-full h-full bg-[#0d0a21] text-purple-100 font-mono text-sm p-4 outline-none resize-none border border-purple-500/20 rounded-2xl leading-relaxed"
                placeholder="Enter HTML/CSS/JS code..."
              />
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
